### ISSUE TITLE
Disable in a specifc filetype

### ISSUE THREAD

**Issue by dantearaujo1** [xiyaowong/virtcolumn.nvim#3]
I can't seem to find how to disable virtcolumn in a specif filetype

**Comment by xiyaowong** [comment]
> I can't seem to find how to disable virtcolumn in a specif filetype

set cc＝0

**Comment by de-abreu** [comment]
> > I can't seem to find how to disable virtcolumn in a specif filetype
> 
> set cc＝0

Can that be done t specific filetypes? I would like for the column to be disabled at every non editable filetype.
