### ISSUE TITLE
Doesn't work in NVIM v0.10.0

### ISSUE THREAD

**Issue by hinell** [xiyaowong/virtcolumn.nvim#5]
![image](https://github.com/xiyaowong/virtcolumn.nvim/assets/8136158/3c5aa515-6f43-4a76-b2fb-058fc12a57fc)
Setup

```
NVIM v0.10.0-dev-daf7abbc42
Build type: MinSizeRel
LuaJIT 2.1.0-beta3
```

**Comment by xiyaowong** [comment]
![image](https://github.com/xiyaowong/virtcolumn.nvim/assets/47070852/6504a0de-accf-4a6e-b66c-29c1f8280c03)

Works fine for me

**Comment by hinell** [comment]
There is no virtual column in that screenshot!

**Comment by hinell** [comment]
I've uploaded screenshot. It doesn't work for me. I've tried various themes.

**Comment by xiyaowong** [comment]
@hinell  What `:echo w:virtcolumn_items` outputs? If it does not exist, then this plugin may not have been loaded; if it is empty, then you need to set the colorcolumn option.

**Comment by hinell** [comment]
@xiyaowong It was empty, yeah! Sorry for bothering.
Please update docs that this config should be setup similarly to `h 'colorcolumn'` nvim option, thanks.

**Comment by hinell** [comment]
@xiyaowong It was empty, yeah! Sorry for bothering.
Please update docs that this config should be setup similarly to `h 'colorcolumn'` nvim option, thanks:

**Comment by xiyaowong** [comment]
@hinell  No, you’ve misunderstood. You should set the “colorcolumn” option properly.

**Comment by xiyaowong** [comment]
The "virtcolumn_items" variable is automatically set based on the "colorcolumn" option. In this case, you do not need to do anything with this variable.

**Comment by hinell** [comment]
@xiyaowong Alright. Just update docs on that. Thanks.
