### ISSUE TITLE
Starts working only after entering the insert mode or closing a floating window

### ISSUE THREAD

**Issue by Andrew15-5** [xiyaowong/virtcolumn.nvim#7]
I was looking just for this plugin, but for some reason it only works after entering insert mode or after closing an opened lazy.nvim floating window. I even set `lazy = false` and the "dirty" `vim.cmd([[au FileType rust setl cc=100]])` (just like in the example) and this didn't help. I use Neovim 0.9.4.

Before the slim line appears, there is a default one column thick `colorcolumn` line.
![image](https://github.com/xiyaowong/virtcolumn.nvim/assets/37143421/da918c7c-5a61-40a0-b357-29145a39c294)
![image](https://github.com/xiyaowong/virtcolumn.nvim/assets/37143421/b2a3894c-3855-44ef-b694-a4b7ee069934)

**Comment by Andrew15-5** [comment]
This didn't fix the problem.

**Comment by xiyaowong** [comment]
@Andrew15-5  Please provide a screen recording

**Comment by Andrew15-5** [comment]
https://github.com/xiyaowong/virtcolumn.nvim/assets/37143421/c0f4f214-eb5b-4c9a-a4d9-4718bde96e39

**Comment by xiyaowong** [comment]
weird, I can't reproduce. Can you try add 'FileType' to the event list?
https://github.com/xiyaowong/virtcolumn.nvim/blob/abffc35d03c9d0a34b8ef2f3fd71352cc993abd6/plugin/virtcolumn.lua#L154

**Comment by Andrew15-5** [comment]
Oh yeah, this fixes it. Strange. I can make a MWA or a Docker image to see if this bug persists, if you want.

**Comment by xiyaowong** [comment]
Try removing `FileType` and then change your autocmd to `vim.cmd([[au FileType rust ++nested setl cc=100]])`

**Comment by Andrew15-5** [comment]
I will answer in a few days.
